REMOTE_URL = 'http://127.0.0.1:4723'
PLATFORM_NAME ='Android'
#DEVICE_NAME = '2c47c2cc'
DEVICE_NAME = '0L02410R200030D8'
APP_PACKAGE = 'com.msil.servizapp'
APP_ACTIVITY = 'com.msil.servizapp.MainActivity'
APP = 'C:\\Users\\manis\\Desktop\\APPIUM\\Maruti-Apk\\app-debug-separate-close-mode-none.apk'
AUTOMATION_NAME = 'UiAutomator2'
USER1_DETAILS = '214248'
LOGIN_USER_FIELD2 = 'xpath=//android.webkit.WebView[@text="ServizApp"]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.widget.EditText'
#${LOGIN_USER_FIELD1}  xpath=//android.webkit.WebView[@text="ServizApp"]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.widget.Image
#${LOGIN_USER_FIELD}   xpath=//android.webkit.WebView[@text="ServizApp"]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View/android.view.View
LOGIN_USER_FIELD3 = 'xpath=//android.webkit.WebView[@text="ServizApp"]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.widget.EditText'
Select_Date_1 = '//android.widget.Button[@text="25"]'
Select_Date_2 = '//android.widget.Button[@text="30"]'
email_report = '//android.webkit.WebView[@text="ServizApp"]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[4]/android.view.View/android.view.View/android.widget.EditText'
cc_email_report = '//android.webkit.WebView[@text="ServizApp"]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[5]/android.view.View/android.view.View/android.widget.EditText'
DIALOG_BUTTON_XPATH1 = '//android.app.Dialog/android.view.View/android.view.View[1]/android.view.View[2]/android.widget.Button'
DIALOG_BUTTON_XPATH2 = '//android.app.Dialog/android.view.View/android.view.View[1]/android.view.View[3]/android.widget.Button'
MAX_CLICKS = '9'  # Number of times to click the dialog button